version: '2'
services:
  web:
    container_name: web-diagrama
    image: nginx:1.13
    links:
      - php
    environment:
      WEB_HOSTNAME: diagrama.local
    ports:
      - "8080:80"
      - "8040:8040"
    volumes:
      - "./etc/nginx/gzip.conf:/etc/nginx/conf.d/gzip.conf"
      - "./etc/nginx/nginx-default.conf:/etc/nginx/conf.d/default.conf"
    volumes_from:
      - php
  php:
    container_name: php-diagrama
    build: ./php
    image: docker_diagrama/php
    links:
      - db
      - redis
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - ../application:/var/www/application
  worker:
    container_name: worker-diagrama
    image: docker_diagrama/worker
    build: ./worker
    environment:
      QUEUE_CONNECTION: redis
      LARAVEL_HORIZON: 'true'
    links:
      - db
      - redis
    volumes:
      - "../application:/var/www/application"
  db:
    container_name: db-diagrama
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: diagrama
      POSTGRES_PASSWORD: q1w2e3
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
  redis:
    container_name: redis-diagrama
    image: redis:latest
    volumes:
      - ./data/redis_data:/data
